import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./static/Header";
import StoreProvider from "./global/storeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className}>
          <Header />
          <main className="w-full flex justify-center">
            <div className="w-[96%] min-h-[85vh] m-4 p-4 border rounded-md">
              {children}
            </div>
          </main>
        </body>
      </html>
    </StoreProvider>
  );
}
